### ISSUE TITLE
Could you give an example of MODEL_PATH?

### ISSUE THREAD

**Issue by realcarlos** [alexrozanski/llama.swift#4]
I saw MODEL_PATH=/path/to/ggml-model-q4_0.bin in README, but not sure how to set the path here .

my model file is : /Users/xxx/llama.swift/models/7B/ggml-model-q4_0.bin

when I run test , it shows:

Enter prompt: 
hi
Initializing model... Enter prompt: 

and nothing happens

**Comment by alexrozanski** [comment]
Hey @realcarlos, There was a bug in the error handling logic which should now be fixed. I suspect the issue is that you're using an incompatible model file (since this version of llama.swift is branched off an old version of llama.cpp)

Try updating to the latest version of llama.swift now and rerunning -- you should get an error message now which should help you to debug.

As I mention in the release notes, the future of llama.swift is [CameLLM](https://github.com/camellm/camellm) which is also based off a newer version of llama.cpp, which might be more suited to you.

**Comment by realcarlos** [comment]
> Hey @realcarlos, There was a bug in the error handling logic which should now be fixed. I suspect the issue is that you're using an incompatible model file (since this version of llama.swift is branched off an old version of llama.cpp)
> 
> Try updating to the latest version of llama.swift now and rerunning -- you should get an error message now which should help you to debug.
> 
> As I mention in the release notes, the future of llama.swift is [CameLLM](https://github.com/camellm/camellm) which is also based off a newer version of llama.cpp, which might be more suited to you.

Got it ,thank you @alexrozanski
